server.port=8081

logging.level.org.skypro.hogwarts=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true